# Generated by Django 3.1.3 on 2020-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcip',
            name='ip',
            field=models.TextField(),
        ),
    ]
