# Generated by Django 3.1.3 on 2020-11-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0003_black_bucket_black_database_black_instance_black_region_black_srcip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Black_Bucket',
        ),
        migrations.DeleteModel(
            name='Black_Database',
        ),
        migrations.DeleteModel(
            name='Black_Instance',
        ),
    ]
