# Generated by Django 3.1.3 on 2020-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0004_auto_20201124_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black_region',
            name='region',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='black_srcip',
            name='ip',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='bucket',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='db',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='srcip',
            name='ip',
            field=models.TextField(unique=True),
        ),
    ]
