# Generated by Django 3.1.3 on 2020-12-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0005_auto_20201126_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessKeyIDPW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesskeyid', models.TextField(unique=True)),
                ('secretaccesskey', models.TextField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Black_Region',
        ),
        migrations.DeleteModel(
            name='Black_SrcIP',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SrcIP',
        ),
    ]
