# Generated by Django 3.1.3 on 2020-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0006_auto_20201216_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskeyidpw',
            name='awsconfigregion',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesskeyidpw',
            name='awsrolename',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
