# Generated by Django 3.1.3 on 2020-11-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201116_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Log',
        ),
    ]
