# Generated by Django 3.1.3 on 2020-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201117_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tag',
            field=models.TextField(blank=True),
        ),
    ]
