# Generated by Django 3.1.3 on 2020-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_log_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automated_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
